### ISSUE TITLE
Support Runtime and Version filtering

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-operator#18]
See https://github.com/fabric8-launcher/launcher-backend/issues/749

The template already supports it: 
https://github.com/fabric8-launcher/launcher-openshift-templates/blob/master/openshift/launcher-template.yaml#L117-L124

**Comment by edewit** [comment]
fixed with: https://github.com/fabric8-launcher/launcher-operator/pull/31
