### ISSUE TITLE
Fix redirect example in instructions

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-operator#20]
Current instructions:

```
$ oc create -f <(echo '
  kind: OAuthClient
  apiVersion: oauth.openshift.io/v1
  metadata:
    name: launcher
  secret: <CHANGE_IT>
  redirectURIs:
    - "https://<your frontend hostname>/"
  grantMethod: prompt
  ')
```

the `redirectURIs` should have `http` in place of `https`, else I get this error when pressing the "Launch" button on the frontend:

``{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."}``

...and URL sticks at:

`https://192.168.99.109:8443/oauth/authorize?client_id=launcher&response_type=token&redirect_uri=http%3A%2F%2Flauncher-launcher.192.168.99.109.nip.io%2Flaunch%2Flogin%3Frequest%3D%2F`

Changing to `http` makes this work on subsequent installs I've done.

Does that makes sense, @ia3andy and @gastaldi ?

**Comment by ia3andy** [comment]
@ALRubinger my bad, I changed it locally but didn't push that.. Sorry.. I am changing it now ;-)
