### ISSUE TITLE
Operator creates unsecure route

### ISSUE THREAD

**Issue by matskiv** [fabric8-launcher/launcher-operator#24]
Operator creates unsecure http route.
This exposes users Openshift and GitHub auth tokens to man-in-the-middle attack.

**Comment by matskiv** [comment]
@ia3andy @gastaldi @edewit ping

**Comment by gastaldi** [comment]
@matskiv that would require changing the Route template here: https://github.com/fabric8-launcher/launcher-application/blob/master/templates/openshift/split/launcher-routes.yaml

Mind providing a PR?
