### ISSUE TITLE
Support catalog filter via CR field

### ISSUE THREAD

**Issue by matskiv** [fabric8-launcher/launcher-operator#26]
Template already contains LAUNCHER_BOOSTER_CATALOG_FILTER field:
https://github.com/fabric8-launcher/launcher-operator/blob/d0124534296c3d1239fb0110ce70876bfe9dd3fa/templates/fabric8-launcher.yaml#L83-L86

Being able to set it via CR would significantly simplify adoption in Integreatly.

**Comment by ia3andy** [comment]
@matskiv I'll try to add this soon, if you want to provide a PR, that would be great!

**Comment by ia3andy** [comment]
@edewit is working on adding:
 ```
LAUNCHER_BOOSTER_CATALOG_REPOSITORY
LAUNCHER_BOOSTER_CATALOG_REF 
LAUNCHER_BOOSTER_CATALOG_FILTER
LAUNCHER_BACKEND_CATALOG_REINDEX_TOKEN
LAUNCHER_FILTER_RUNTIME
LAUNCHER_FILTER_VERSION
```
